#Melody Game

#######Notes
#Use sprits in the form of square for each key


#Psuedocode:

#1. Create a list of melodies (each melody is a list of notes)
#2. Each button has a sound for a melody
#3. When a button is pressed, play the corresponding melody, in which each button is presssed by the computer in corresponding order to the melody
#4. The player must repeat the melody by pressing the buttons in the correct order
#5. If the player presses the correct buttons in the correct order, they move on to the next melody
#6. If the player presses the wrong button, they get a strike counter added to them, and they have to start the melody over again
#7 If the player gets 3 strikes, they lose and have to start the game over again

import pygame
import random
import sys
import time

pygame.init()

COLOR = (255, 255, 255)        
SURFACE_COLOR = (115, 147, 179) 
WIDTH = 800
HEIGHT = 800

#Everything below is imported from https://www.geeksforgeeks.org/python/pygame-creating-sprites/ and modified to fit my game, I will be using sprites for the buttons that the user will press to play the melodies

#Make Sprites

class Sprite(pygame.sprite.Sprite):
    def __init__(self, color, height, width):
        super().__init__()

        self.image = pygame.Surface([width, height])
        self.image.fill(SURFACE_COLOR)
        self.image.set_colorkey(COLOR)

        pygame.draw.rect(self.image, color, pygame.Rect(0, 0, width, height))

        self.rect = self.image.get_rect()

class ClickableSprite(pygame.sprite.Sprite):
    def __init__(self, image, x, y):
        super().__init__()
        self.image = image
        self.rect = self.image.get_rect(topleft=(x, y))

    def handle_event(self, event):
        if event.type == pygame.MOUSEBUTTONDOWN:
            # Check if the mouse click position (event.pos) is inside the sprite
            if self.rect.collidepoint(event.pos):
                print("Sprite clicked!")
               


RED = (255, 0, 0)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

size = (WIDTH, HEIGHT)
screen = pygame.display.set_mode(size)
pygame.display.set_caption("Melody Game")

all_sprites_list = pygame.sprite.Group()

#Create Objects
object1 = Sprite(RED, 20, 30)
object2 = Sprite(BLACK, 20, 30)
object3 = Sprite(RED, 20, 30)
object4 = Sprite(BLACK, 20, 30)
object5 = Sprite(RED, 20, 30)

#Set the position of the objects
object1.rect.x = 100  
object1.rect.y = 300  
object2.rect.x = 200
object2.rect.y = 300
object3.rect.x = 300
object3.rect.y = 300
object4.rect.x = 400
object4.rect.y = 300
object5.rect.x = 500
object5.rect.y = 300

#Add the objects to the list of sprites
all_sprites_list.add(object1)
all_sprites_list.add(object2)
all_sprites_list.add(object3)
all_sprites_list.add(object4)
all_sprites_list.add(object5)

exit_game = True
clock = pygame.time.Clock()
print (clock)

sprite_objects = [object1, object2, object3, object4, object5]
game_over = False

while exit_game:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            exit_game = False
        elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1 and not game_over:
            for i, obj in enumerate(sprite_objects, start=1): #Generated by ChatGPT, modified to fit my game
                if obj.rect.collidepoint(event.pos):
                    print(f"Sprite{i} clicked!")
                    #Play the corresponding sound for the sprite
                    #Add the corresponding note to the melody list that the player has to repeat
                    break

    all_sprites_list.update()
    screen.fill(SURFACE_COLOR)
    all_sprites_list.draw(screen)
    pygame.display.flip()
    clock.tick(60)

pygame.quit()
sys.exit()

