#Melody Game

#######Notes
#Use sprits in the form of square for each key


#Psuedocode:

#1. Create a list of melodies (each melody is a list of notes)
#2. Each button has a sound for a melody
#3. When a button is pressed, play the corresponding melody, in which each button is presssed by the computer in corresponding order to the melody
#4. The player must repeat the melody by pressing the buttons in the correct order
#5. If the player presses the correct buttons in the correct order, they move on to the next melody
#6. If the player presses the wrong button, they get a strike counter added to them, and they have to start the melody over again
#7 If the player gets 3 strikes, they lose and have to start the game over again

import pygame
import random
import sys
import numpy as np

pygame.mixer.pre_init(frequency=44100, size=-16, channels=2, buffer=512)
pygame.init()
pygame.mixer.init()

# all of the sound effects in this game were generated by Claude (Lines 29-138)

def make_hooray_sound(sample_rate=44100, volume=0.35):
    #Ascending C-E-G-C arpeggio for a cheerful "hooray"
    notes = [(523.25, 0.12), (659.25, 0.12), (783.99, 0.12), (1046.50, 0.28)]
    pieces = []
    for freq, dur in notes:
        t = np.linspace(0, dur, int(sample_rate * dur), endpoint=False)
        tone = np.sin(2 * np.pi * freq * t)
        fade = int(sample_rate * 0.01)
        env = np.ones_like(tone)
        env[:fade] = np.linspace(0, 1, fade)
        env[-fade:] = np.linspace(1, 0, fade)
        pieces.append(tone * env)
    wave = np.concatenate(pieces) * volume
    audio = np.int16(wave * 32767)
    stereo = np.column_stack((audio, audio))
    return pygame.sndarray.make_sound(stereo)

def make_anthem_sound(sample_rate=44100, volume=0.38):
    #Short triumphant fanfare in C major: da-da-da-DAAA-da-DAAA
    #(freq_hz, duration_seconds) pairs — rests use freq=0
    notes = [
        (523.25, 0.10),  # C5
        (659.25, 0.10),  # E5
        (783.99, 0.10),  # G5
        (1046.50, 0.30), # C6 held
        (0.0,    0.05),  # tiny breath
        (783.99, 0.10),  # G5
        (1046.50, 0.45), # C6 held long
    ]
    pieces = []
    for freq, dur in notes:
        t = np.linspace(0, dur, int(sample_rate * dur), endpoint=False)
        if freq <= 0:
            tone = np.zeros_like(t)
        else:
            #Stacked harmonics for a brassy anthem feel
            tone = (np.sin(2 * np.pi * freq * t)
                    + 0.5 * np.sin(2 * np.pi * 2 * freq * t)
                    + 0.25 * np.sin(2 * np.pi * 3 * freq * t))
            tone = tone / 1.75
            fade = int(sample_rate * 0.012)
            env = np.ones_like(tone)
            env[:fade] = np.linspace(0, 1, fade)
            env[-fade:] = np.linspace(1, 0, fade)
            tone = tone * env
        pieces.append(tone)
    wave = np.concatenate(pieces) * volume
    audio = np.int16(np.clip(wave, -1.0, 1.0) * 32767)
    stereo = np.column_stack((audio, audio))
    return pygame.sndarray.make_sound(stereo)

def make_whomp_sound(sample_rate=44100, volume=0.35):
    #Descending "sad trombone" whomp-whomp-whomp-whoooomp
    notes = [(261.63, 0.22), (233.08, 0.22), (207.65, 0.22), (174.61, 0.55)]
    pieces = []
    for freq, dur in notes:
        t = np.linspace(0, dur, int(sample_rate * dur), endpoint=False)
        #Slight vibrato + saw-ish flavor for a brassy feel
        tone = (np.sin(2 * np.pi * freq * t)
                + 0.5 * np.sin(2 * np.pi * 2 * freq * t)
                + 0.25 * np.sin(2 * np.pi * 3 * freq * t))
        tone = tone / 1.75
        fade = int(sample_rate * 0.015)
        env = np.ones_like(tone)
        env[:fade] = np.linspace(0, 1, fade)
        env[-fade:] = np.linspace(1, 0, fade)
        pieces.append(tone * env)
        #Small silent gap between whomps
        pieces.append(np.zeros(int(sample_rate * 0.04)))
    wave = np.concatenate(pieces) * volume
    audio = np.int16(wave * 32767)
    stereo = np.column_stack((audio, audio))
    return pygame.sndarray.make_sound(stereo)

def make_button_press_sound(sample_rate=44100, volume=0.4):
    #Short keypad-style "beep" with a tiny mechanical click for a safe-button feel
    click_dur = 0.012
    beep_dur = 0.09
    t_click = np.linspace(0, click_dur, int(sample_rate * click_dur), endpoint=False)
    click = np.sign(np.sin(2 * np.pi * 1800 * t_click)) * np.linspace(1, 0, len(t_click)) * 0.6
    t_beep = np.linspace(0, beep_dur, int(sample_rate * beep_dur), endpoint=False)
    beep = np.sin(2 * np.pi * 880 * t_beep)
    fade = int(sample_rate * 0.008)
    env = np.ones_like(beep)
    env[:fade] = np.linspace(0, 1, fade)
    env[-fade:] = np.linspace(1, 0, fade)
    beep = beep * env
    wave = np.concatenate([click, beep]) * volume
    audio = np.int16(np.clip(wave, -1.0, 1.0) * 32767)
    stereo = np.column_stack((audio, audio))
    return pygame.sndarray.make_sound(stereo)

def make_buzzer_sound(duration=0.5, sample_rate=44100, volume=0.35):
    #Harsh low square-wave buzzer for wrong answers
    t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)
    wave = np.sign(np.sin(2 * np.pi * 140 * t)) * 0.6
    wave += np.sign(np.sin(2 * np.pi * 95 * t)) * 0.4
    fade = int(sample_rate * 0.02)
    env = np.ones_like(wave)
    env[:fade] = np.linspace(0, 1, fade)
    env[-fade:] = np.linspace(1, 0, fade)
    wave = wave * env * volume
    audio = np.int16(wave * 32767)
    stereo = np.column_stack((audio, audio))
    return pygame.sndarray.make_sound(stereo)

# colors and screen dimensions 

COLOR = (255, 255, 255)
SURFACE_COLOR = (115, 147, 179) 
WIDTH = 800
HEIGHT = 800

# everything below is imported from https://www.geeksforgeeks.org/python/pygame-creating-sprites/ and modified to fit my game, I will be using sprites for the buttons that the user will press to play the melodies

# make Sprites

HIGHLIGHT_COLOR = (255, 255, 0)  # yellow flash, visible on both red and black sprites
HIGHLIGHT_MS = 350

class Sprite(pygame.sprite.Sprite): #https://www.pygame.org/docs/ref/sprite.html#:~:text=The%20initializer%20can%20accept%20any,can%20be%20passed%20as%20arguments.
    def __init__(self, color, width, height):
        super().__init__()

        white_img = pygame.image.load("img_keys//white_key.png").convert_alpha()
        black_img = pygame.image.load("img_keys//black_key.png").convert_alpha()
        red_img = pygame.image.load("img_keys//red_key.png").convert_alpha()

        if color == WHITE:
            self.base_image = pygame.transform.scale(white_img, (width, height))
        else:
            self.base_image = pygame.transform.scale(black_img, (width, height))

        self.highlight_image = pygame.transform.scale(red_img, (width, height))

        self.image = self.base_image
        self.rect = self.image.get_rect()
        self.highlight_until = 0

    # used Code from https://www.pygame.org/docs/ref/sprite.html#pygame.sprite.Sprite.update and modified it to fit my game, this is used to make the sprites flash when they are pressed by the computer or the user
    def highlight(self, now):
        self.image = self.highlight_image
        self.highlight_until = now + HIGHLIGHT_MS

    def update_highlight(self, now):
        if self.highlight_until and now >= self.highlight_until:
            self.image = self.base_image
            self.highlight_until = 0

class ClickableSprite(pygame.sprite.Sprite):
    def __init__(self, image, x, y):
        super().__init__()
        self.image = image
        self.rect = self.image.get_rect(topleft=(x, y))



RED = (255, 0, 0)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

size = (WIDTH, HEIGHT)
screen = pygame.display.set_mode(size)
pygame.display.set_caption("Melody Game")

all_sprites_list = pygame.sprite.Group()

# 3 rows x 4 cols grid of buttons 
GRID_COLS = 3
GRID_ROWS = 4
NUM_BUTTONS = GRID_COLS * GRID_ROWS
BUTTON_W = 140
BUTTON_H = 120
BUTTON_GAP_X = 30
BUTTON_GAP_Y = 20
grid_total_w = GRID_COLS * BUTTON_W + (GRID_COLS - 1) * BUTTON_GAP_X
grid_total_h = GRID_ROWS * BUTTON_H + (GRID_ROWS - 1) * BUTTON_GAP_Y
grid_origin_x = (WIDTH - grid_total_w) // 2
grid_origin_y = 220

sprite_objects = []
for row in range(GRID_ROWS):
    for col in range(GRID_COLS):
        color = WHITE if (row + col) % 2 == 0 else BLACK
        obj = Sprite(color, BUTTON_W, BUTTON_H)
        obj.rect.x = grid_origin_x + col * (BUTTON_W + BUTTON_GAP_X)
        obj.rect.y = grid_origin_y + row * (BUTTON_H + BUTTON_GAP_Y)
        all_sprites_list.add(obj)
        sprite_objects.append(obj)

exit_game = True
clock = pygame.time.Clock()
print (clock)

#timer text
timer_font = pygame.font.SysFont("Arial", 48, bold=True)
TIMER_COLOR = (255, 255, 255)
game_start_ticks = pygame.time.get_ticks()



hooray_sound = make_hooray_sound()
anthem_sound = make_anthem_sound()
buzzer_sound = make_buzzer_sound()
whomp_sound = make_whomp_sound()
button_press_sound = make_button_press_sound()

# constants and variables for game state
rounds = 0
strikes = 0
max_strikes = 3
game_over = False
won = False

melody = []
player_melody = []
final_melody = [] #add list for the final round combination
state = "start_round"    # "start_round" -> "computer_playing" -> "player_input" -> "check" -> "between_rounds" (Planned by Claude)
next_note_time = 0
next_round_time = 0
check_time = 0
chord_gap_ms = 800        # time between computer-played chords
between_rounds_ms = 1000  # pause after a round so the last highlight stays visible
pre_result_ms = 250       # tiny beat between the last click and the win/lose sound
timer = 0

while exit_game:
    now = pygame.time.get_ticks()

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            exit_game = False
        elif event.type == pygame.KEYDOWN and not game_over and state in ("player_input", "final_input"):
            key_to_index = {
                pygame.K_1: 0, pygame.K_2: 1, pygame.K_3: 2, pygame.K_4: 3,
                pygame.K_5: 4, pygame.K_6: 5, pygame.K_7: 6, pygame.K_8: 7,
                pygame.K_9: 8, pygame.K_a: 9, pygame.K_0: 10, pygame.K_b: 11,
            }
            if event.key in key_to_index:
                i = key_to_index[event.key]
                obj = sprite_objects[i]
                button_press_sound.play()
                obj.highlight(now)
                player_melody.append(i)
                target = final_melody if state == "final_input" else melody #generated by Claude to fix final_melody bug
                if len(player_melody) >= len(target):
                    if state == "final_input":
                        state = "final_check"
                    else:
                        state = "check"
                    check_time = now + pre_result_ms

    if not game_over:
        if state == "start_round":
            if rounds <= 3:
                melody_length = rounds + 1
                melody = [random.randrange(NUM_BUTTONS) for _ in range(melody_length)]
                player_melody = []
                note_index = 0
                next_note_time = now
                print(f"Round {rounds + 1}: Listen to the melody! ({melody})")
                state = "computer_playing"
            else:
                player_melody = []
                print(f"Final round! Input the {len(final_melody)}-digit combination: {final_melody}")
                state = "final_input" #last game where combination must be put in correct order to win

        elif state == "computer_playing": # computer plays the keys
            if now >= next_note_time:
                if note_index < len(melody):
                    btn_idx = melody[note_index]
                    button_press_sound.play()
                    sprite_objects[btn_idx].highlight(now)
                    note_index += 1
                    next_note_time = now + chord_gap_ms
                else:
                    print("Your turn — repeat the melody!")
                    state = "player_input"

        elif state == "check": # algorithm checks if keys were played in correct order
            if now >= check_time:
                if player_melody == melody:
                    print("Correct! Next round.")
                    hooray_sound.play()
                    final_melody.append(melody[0])
                    rounds += 1
                else:
                    strikes += 1
                    print(f"Wrong! Strike {strikes}/{max_strikes}.")
                    buzzer_sound.play()
                    if strikes >= max_strikes:
                        print("Game over!")
                        game_over = True
                        whomp_sound.play()
                if not game_over: # adds a buffer between rounds so the last highlight stays visible before the next melody starts
                    state = "between_rounds"
                    next_round_time = now + between_rounds_ms
        
        elif state == "final_check": # checks if the final combination was inputted correctly, if so player wins, if not, player gets a strike and has to try the final round again until they get 3 strikes and lose or they win by getting the combination correct
            if now >= check_time:
                if player_melody == final_melody:
                    print("Correct, YOU WIN")
                    anthem_sound.play()
                    won = True
                    game_over = True
                else:
                    strikes += 1
                    print(f"Wrong! Strike {strikes}/{max_strikes}.")
                    buzzer_sound.play()
                    player_melody = []
                    if strikes >= max_strikes:
                        print("Game over!")
                        game_over = True
                        whomp_sound.play()
                    else:
                        state = "final_input"

        elif state == "between_rounds": 
            if now >= next_round_time:
                state = "start_round"

    for s in sprite_objects:
        s.update_highlight(now)

    all_sprites_list.update()
    screen.fill(SURFACE_COLOR)
    all_sprites_list.draw(screen)

    if not game_over:
        round_text = timer_font.render(f"Round: {rounds + 1}", True, TIMER_COLOR)
        screen.blit(round_text, (WIDTH - round_text.get_width() - 20, 80))
        strike_text = timer_font.render(f"Strikes: {strikes}/{max_strikes}", True, (255, 0, 0))
        screen.blit(strike_text, (WIDTH - strike_text.get_width() - 20, 140))
        if state in ("final_input", "final_check"):
            prompt_text = timer_font.render("Input the Combination!", True, (255, 215, 0))
            screen.blit(prompt_text, ((WIDTH - prompt_text.get_width()) // 2, 100))

    elif won:
        win_text = timer_font.render("Congratulations! You won!", True, (0, 255, 0))
        screen.blit(win_text, ((WIDTH - win_text.get_width()) // 2, 100))

    else:
        lost_text = timer_font.render("Game Over! Try Again!", True, (255, 0, 0))
        screen.blit(lost_text, ((WIDTH - lost_text.get_width()) // 2, 100))
        
    # draw the elapsed-time timer in the top-right
    time_left = 360000 - (now - game_start_ticks)  # 60 seconds total, converted to milliseconds
    seconds_total = time_left // 1000
    timer_text = f"{seconds_total // 60:02d}:{seconds_total % 60:02d}"
    if time_left <= 0:
        if not game_over:
            whomp_sound.play()
            game_over = True
            for sprite in list(all_sprites_list):
                sprite.remove()  # remove sprites to prevent further interaction
            sprite_objects.clear()  # clear the list of sprites
        timer_text = "00:00"
        timer_surface = timer_font.render(timer_text, True, (255, 0, 0))  # red timer when time's up
        lost_text = timer_font.render("Time's up! Game Over!", True, (255, 0, 0))
        screen.blit(lost_text, ((WIDTH - lost_text.get_width()) // 2, 100))

    else:
        timer_text = f"{seconds_total // 60:02d}:{seconds_total % 60:02d}"

   
    timer_surface = timer_font.render(timer_text, True, TIMER_COLOR)
    screen.blit(timer_surface, (WIDTH - timer_surface.get_width() - 20, 20))

    pygame.display.flip()
    clock.tick(60)

pygame.quit()
sys.exit()