#Melody Game

#######Notes
#Use sprits in the form of square for each key


#Psuedocode:

#1. Create a list of melodies (each melody is a list of notes)
#2. Each button has a sound for a melody
#3. When a button is pressed, play the corresponding melody, in which each button is presssed by the computer in corresponding order to the melody
#4. The player must repeat the melody by pressing the buttons in the correct order
#5. If the player presses the correct buttons in the correct order, they move on to the next melody
#6. If the player presses the wrong button, they get a strike counter added to them, and they have to start the melody over again
#7 If the player gets 3 strikes, they lose and have to start the game over again

import pygame
import random
import sys
import numpy as np
from bomb_configs import *
from character_overlay import draw_character
from display_utils import create_fullscreen_display

pygame.mixer.pre_init(frequency=44100, size=-16, channels=2, buffer=512)
# pygame.init()
# pygame.mixer.init()

# all of the sound effects in this game were generated by Claude (Lines 29-138)

def make_hooray_sound(sample_rate=44100, volume=10.00):
    #Ascending C-E-G-C arpeggio for a cheerful "hooray"
    notes = [(523.25, 0.12), (659.25, 0.12), (783.99, 0.12), (1046.50, 0.28)]
    pieces = []
    for freq, dur in notes:
        t = np.linspace(0, dur, int(sample_rate * dur), endpoint=False)
        tone = np.sin(2 * np.pi * freq * t)
        fade = int(sample_rate * 0.01)
        env = np.ones_like(tone)
        env[:fade] = np.linspace(0, 1, fade)
        env[-fade:] = np.linspace(1, 0, fade)
        pieces.append(tone * env)
    wave = np.concatenate(pieces) * volume
    audio = np.int16(wave * 32767)
    stereo = np.column_stack((audio, audio))
    return pygame.sndarray.make_sound(stereo)

def make_anthem_sound(sample_rate=44100, volume=10.00):
    #Short triumphant fanfare in C major: da-da-da-DAAA-da-DAAA
    #(freq_hz, duration_seconds) pairs — rests use freq=0
    notes = [
        (523.25, 0.10),  # C5
        (659.25, 0.10),  # E5
        (783.99, 0.10),  # G5
        (1046.50, 0.30), # C6 held
        (0.0,    0.05),  # tiny breath
        (783.99, 0.10),  # G5
        (1046.50, 0.45), # C6 held long
    ]
    pieces = []
    for freq, dur in notes:
        t = np.linspace(0, dur, int(sample_rate * dur), endpoint=False)
        if freq <= 0:
            tone = np.zeros_like(t)
        else:
            #Stacked harmonics for a brassy anthem feel
            tone = (np.sin(2 * np.pi * freq * t)
                    + 0.5 * np.sin(2 * np.pi * 2 * freq * t)
                    + 0.25 * np.sin(2 * np.pi * 3 * freq * t))
            tone = tone / 1.75
            fade = int(sample_rate * 0.012)
            env = np.ones_like(tone)
            env[:fade] = np.linspace(0, 1, fade)
            env[-fade:] = np.linspace(1, 0, fade)
            tone = tone * env
        pieces.append(tone)
    wave = np.concatenate(pieces) * volume
    audio = np.int16(np.clip(wave, -1.0, 1.0) * 32767)
    stereo = np.column_stack((audio, audio))
    return pygame.sndarray.make_sound(stereo)

def make_whomp_sound(sample_rate=44100, volume=10.00):
    #Descending "sad trombone" whomp-whomp-whomp-whoooomp
    notes = [(261.63, 0.22), (233.08, 0.22), (207.65, 0.22), (174.61, 0.55)]
    pieces = []
    for freq, dur in notes:
        t = np.linspace(0, dur, int(sample_rate * dur), endpoint=False)
        #Slight vibrato + saw-ish flavor for a brassy feel
        tone = (np.sin(2 * np.pi * freq * t)
                + 0.5 * np.sin(2 * np.pi * 2 * freq * t)
                + 0.25 * np.sin(2 * np.pi * 3 * freq * t))
        tone = tone / 1.75
        fade = int(sample_rate * 0.015)
        env = np.ones_like(tone)
        env[:fade] = np.linspace(0, 1, fade)
        env[-fade:] = np.linspace(1, 0, fade)
        pieces.append(tone * env)
        #Small silent gap between whomps
        pieces.append(np.zeros(int(sample_rate * 0.04)))
    wave = np.concatenate(pieces) * volume
    audio = np.int16(wave * 32767)
    stereo = np.column_stack((audio, audio))
    return pygame.sndarray.make_sound(stereo)

def make_button_press_sound(sample_rate=44100, volume=10.00):
    #Short keypad-style "beep" with a tiny mechanical click for a safe-button feel
    click_dur = 0.012
    beep_dur = 0.09
    t_click = np.linspace(0, click_dur, int(sample_rate * click_dur), endpoint=False)
    click = np.sign(np.sin(2 * np.pi * 1800 * t_click)) * np.linspace(1, 0, len(t_click)) * 0.6
    t_beep = np.linspace(0, beep_dur, int(sample_rate * beep_dur), endpoint=False)
    beep = np.sin(2 * np.pi * 880 * t_beep)
    fade = int(sample_rate * 0.008)
    env = np.ones_like(beep)
    env[:fade] = np.linspace(0, 1, fade)
    env[-fade:] = np.linspace(1, 0, fade)
    beep = beep * env
    wave = np.concatenate([click, beep]) * volume
    audio = np.int16(np.clip(wave, -1.0, 1.0) * 32767)
    stereo = np.column_stack((audio, audio))
    return pygame.sndarray.make_sound(stereo)

def make_buzzer_sound(duration=0.5, sample_rate=44100, volume=10.00):
    #Harsh low square-wave buzzer for wrong answers
    t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)
    wave = np.sign(np.sin(2 * np.pi * 140 * t)) * 0.6
    wave += np.sign(np.sin(2 * np.pi * 95 * t)) * 0.4
    fade = int(sample_rate * 0.02)
    env = np.ones_like(wave)
    env[:fade] = np.linspace(0, 1, fade)
    env[-fade:] = np.linspace(1, 0, fade)
    wave = wave * env * volume
    audio = np.int16(wave * 32767)
    stereo = np.column_stack((audio, audio))
    return pygame.sndarray.make_sound(stereo)

# colors and screen dimensions 

COLOR = (255, 255, 255)
SURFACE_COLOR = (0, 0, 0, 0)
WIDTH = 1024
HEIGHT = 576

MINIGAME_WINDOW_X = 409
MINIGAME_WINDOW_Y = 249
MINIGAME_WINDOW_W = 200
MINIGAME_WINDOW_H = 268

KEYPAD_PANEL_W = 200
KEYPAD_PANEL_H = 300

WIRE_BG_X = 300
WIRE_BG_Y = 232
WIRE_BG_WIDTH = 425
WIRE_BG_HEIGHT = 299

TEXTBOX_X = 277
TEXTBOX_Y = 42
TEXTBOX_WIDTH = 471
TEXTBOX_HEIGHT = 132
TEXTBOX_ALPHA = 180

# everything below is imported from https://www.geeksforgeeks.org/python/pygame-creating-sprites/ and modified to fit my game, I will be using sprites for the buttons that the user will press to play the melodies

# make Sprites

HIGHLIGHT_COLOR = (255, 255, 0)  # yellow flash, visible on both red and black sprites
HIGHLIGHT_MS = 350

class Sprite(pygame.sprite.Sprite): #https://www.pygame.org/docs/ref/sprite.html#:~:text=The%20initializer%20can%20accept%20any,can%20be%20passed%20as%20arguments.
    def __init__(self, color, width, height):
        super().__init__()

        white_img = pygame.image.load("img_keys//white_key.png").convert_alpha()
        black_img = pygame.image.load("img_keys//black_key.png").convert_alpha()
        red_img = pygame.image.load("img_keys//red_key.png").convert_alpha()
        
        white_img.set_alpha(0)
        black_img.set_alpha(0)
        red_img.set_alpha(128)

        if color == WHITE:
            self.base_image = pygame.transform.scale(white_img, (width, height))
        else:
            self.base_image = pygame.transform.scale(black_img, (width, height))

        self.highlight_image = pygame.transform.scale(red_img, (width, height))

        self.image = self.base_image
        self.rect = self.image.get_rect()
        self.highlight_until = 0

    # used Code from https://www.pygame.org/docs/ref/sprite.html#pygame.sprite.Sprite.update and modified it to fit my game, this is used to make the sprites flash when they are pressed by the computer or the user
    def highlight(self, now):
        self.image = self.highlight_image
        self.highlight_until = now + HIGHLIGHT_MS

    def update_highlight(self, now):
        if self.highlight_until and now >= self.highlight_until:
            self.image = self.base_image
            self.highlight_until = 0

class ClickableSprite(pygame.sprite.Sprite):
    def __init__(self, image, x, y):
        super().__init__()
        self.image = image
        self.rect = self.image.get_rect(topleft=(x, y))

    def handle_event(self, event):
        if event.type == pygame.MOUSEBUTTONDOWN:
            # Check if the mouse click position (event.pos) is inside the sprite
            if self.rect.collidepoint(event.pos):
                print("Sprite clicked!")
               


RED = (255, 0, 0)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)


def main(screen=None, clock=None):
    if not pygame.get_init():
        pygame.init()

    if not pygame.mixer.get_init():
        pygame.mixer.init()

    created_display = screen is None
    if screen is None:
        screen = create_fullscreen_display("Safe Game")

    main_screen = screen
    game_surface = pygame.Surface((KEYPAD_PANEL_W, KEYPAD_PANEL_H), pygame.SRCALPHA)
    screen = game_surface

    intro_bg = pygame.image.load("img_keys/base.png").convert()
    intro_bg = pygame.transform.scale(intro_bg, main_screen.get_size())

    wire_bg = pygame.image.load("img_keys/WireBG.png").convert()
    wire_bg = pygame.transform.smoothscale(
        wire_bg,
        (WIRE_BG_WIDTH, WIRE_BG_HEIGHT)
    )
    minigame_rect = pygame.Rect(
        MINIGAME_WINDOW_X,
        MINIGAME_WINDOW_Y,
        MINIGAME_WINDOW_W,
        MINIGAME_WINDOW_H
)

    def show_frame():
        main_screen.blit(intro_bg, (0, 0))
        draw_character(main_screen)
        main_screen.blit(wire_bg, (WIRE_BG_X, WIRE_BG_Y))

        text_box = pygame.Surface((TEXTBOX_WIDTH, TEXTBOX_HEIGHT), pygame.SRCALPHA)
        text_box.fill((0, 0, 0, TEXTBOX_ALPHA))
        main_screen.blit(text_box, (TEXTBOX_X, TEXTBOX_Y))

        border_rect = pygame.Rect(TEXTBOX_X, TEXTBOX_Y, TEXTBOX_WIDTH, TEXTBOX_HEIGHT)
        pygame.draw.rect(main_screen, (255, 255, 255), border_rect, 2)

        scaled_game = pygame.transform.smoothscale(game_surface, minigame_rect.size)
        main_screen.blit(scaled_game, minigame_rect)
        pygame.display.flip()

    all_sprites_list = pygame.sprite.Group()

    # 3 rows x 4 cols grid of buttons
    GRID_COLS = 3
    GRID_ROWS = 4
    NUM_BUTTONS = GRID_COLS * GRID_ROWS
    BUTTON_W = 50
    BUTTON_H = 50
    BUTTON_GAP_X = 3
    BUTTON_GAP_Y = 2

    keypad_panel_w = KEYPAD_PANEL_W
    keypad_panel_h = KEYPAD_PANEL_H
    keypad_origin_x = 0
    keypad_origin_y = 0

    grid_total_w = GRID_COLS * BUTTON_W + (GRID_COLS - 1) * BUTTON_GAP_X
    grid_total_h = GRID_ROWS * BUTTON_H + (GRID_ROWS - 1) * BUTTON_GAP_Y
    grid_origin_x = keypad_origin_x + (keypad_panel_w - grid_total_w) // 2
    grid_origin_y = keypad_origin_y + 71

    sprite_objects = []
    for row in range(GRID_ROWS):
        for col in range(GRID_COLS):
            color = WHITE if (row + col) % 2 == 0 else BLACK
            obj = Sprite(color, BUTTON_W, BUTTON_H)
            obj.rect.x = grid_origin_x + col * (BUTTON_W + BUTTON_GAP_X)
            obj.rect.y = grid_origin_y + row * (BUTTON_H + BUTTON_GAP_Y)
            all_sprites_list.add(obj)
            sprite_objects.append(obj)

    exit_game = True

    if clock is None:
        clock = pygame.time.Clock()

    print(clock)

    # timer text
    timer_font = pygame.font.Font("img_keys//Baskic8.otf", 24)
    TIMER_COLOR = (255, 255, 255)
    game_start_ticks = pygame.time.get_ticks()

    hooray_sound = make_hooray_sound()
    anthem_sound = make_anthem_sound()
    buzzer_sound = make_buzzer_sound()
    whomp_sound = make_whomp_sound()
    button_press_sound = make_button_press_sound()

    # constants and variables for game state
    rounds = 0
    strikes = 0
    max_strikes = 3
    game_over = False
    won = False

    KeyBg = pygame.image.load("img_keys//KeypadFull.png").convert_alpha()
    KeyBg.set_colorkey((0, 0, 0))
    KeyBg = pygame.transform.scale(KeyBg, (keypad_panel_w, keypad_panel_h))
    melody = []
    player_melody = []
    final_melody = []
    state = "start_round"
    note_index = 0
    next_note_time = 0
    next_round_time = 0
    check_time = 0
    chord_gap_ms = 800
    between_rounds_ms = 1000
    pre_result_ms = 250
    striketime = 180

    # map keypad characters to the grid index of their corresponding sprite button
    KEYPAD_LAYOUT = keypad_keys if RPi else ((1, 2, 3), (4, 5, 6), (7, 8, 9), ("*", 0, "#"))
    key_to_index = {}
    _idx = 0
    for _row in KEYPAD_LAYOUT:
        for _k in _row:
            key_to_index[_k] = _idx
            _idx += 1

    last_pressed = None

    while exit_game:
        now = pygame.time.get_ticks()

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                if created_display:
                    pygame.quit()
                return False

        # read the matrix keypad directly
        if RPi:
            pressed = component_keypad.pressed_keys
        else:
            pressed = []

        if pressed:
            if last_pressed is None and not game_over and state in ("player_input", "final_input"):
                key = pressed[0]
                last_pressed = key
                if key in key_to_index:
                    i = key_to_index[key]
                    sprite_objects[i].highlight(now)
                    button_press_sound.play()
                    player_melody.append(i)
                    target = final_melody if state == "final_input" else melody
                    if len(player_melody) >= len(target):
                        state = "final_check" if state == "final_input" else "check"
                        check_time = now + pre_result_ms
            elif last_pressed is None:
                last_pressed = pressed[0]
        else:
            last_pressed = None

        if not game_over:
            if state == "start_round":
                if rounds <= 5:
                    melody_length = rounds + 1
                    melody = [random.randrange(NUM_BUTTONS) for _ in range(melody_length)]
                    player_melody = []
                    note_index = 0
                    next_note_time = now
                    print(f"Round {rounds + 1}: Listen to the melody! ({melody})")
                    state = "computer_playing"
                else:
                    player_melody = []
                    print(f"Final round! Input the {len(final_melody)}-digit combination: {final_melody}")
                    state = "final_input"

            elif state == "computer_playing":
                if now >= next_note_time:
                    if note_index < len(melody):
                        btn_idx = melody[note_index]
                        button_press_sound.play()
                        sprite_objects[btn_idx].highlight(now)
                        note_index += 1
                        next_note_time = now + chord_gap_ms
                    else:
                        print("Your turn — repeat the melody!")
                        state = "player_input"

            elif state == "check":
                if now >= check_time:
                    if player_melody == melody:
                        print("Correct! Next round.")
                        hooray_sound.play()
                        final_melody.append(melody[0])
                        rounds += 1
                    else:
                        strikes += 1
                        print(f"Wrong! Strike {strikes}/{max_strikes}.")
                        striketime = 0
                        buzzer_sound.play()
                        if strikes >= max_strikes:
                            print("Game over!")
                            game_over = True
                            won = False
                            whomp_sound.play()

                    if not game_over:
                        state = "between_rounds"
                        next_round_time = now + between_rounds_ms

            elif state == "final_check":
                if now >= check_time:
                    if player_melody == final_melody:
                        print("Correct, YOU WIN")
                        anthem_sound.play()
                        won = True
                        game_over = True
                    else:
                        strikes += 1
                        print(f"Wrong! Strike {strikes}/{max_strikes}.")
                        buzzer_sound.play()
                        player_melody = []
                        if strikes >= max_strikes:
                            print("Game over!")
                            won = False
                            game_over = True
                            whomp_sound.play()
                        else:
                            state = "final_input"

            elif state == "between_rounds":
                if now >= next_round_time:
                    state = "start_round"

        for s in sprite_objects:
            s.update_highlight(now)

        all_sprites_list.update()
        screen.fill(SURFACE_COLOR)
        screen.blit(KeyBg, (keypad_origin_x, keypad_origin_y))
        all_sprites_list.draw(screen)

        text_x = keypad_origin_x + 28
        text_y = keypad_origin_y + 30

        if not game_over:
            round_text = timer_font.render(f"Round: {rounds + 1}", True, TIMER_COLOR)
            strike_text = timer_font.render(f"Strikes: {strikes}/{max_strikes}", True, (255, 0, 0))

            if striketime < 60:
                striketime += 1
                screen.blit(strike_text, (text_x, text_y))
            elif rounds != 4:
                screen.blit(round_text, (text_x, text_y))

            if state in ("final_input", "final_check"):
                prompt_text = timer_font.render("Combination?", True, (255, 215, 0))
                screen.blit(prompt_text, (text_x, text_y))

        elif won:
            win_text = timer_font.render("Pass!", True, (0, 255, 0))
            screen.blit(win_text, (text_x, text_y))
            show_frame()
            pygame.time.wait(1000)

            if created_display:
                pygame.quit()

            return won
        else:
            lost_text = timer_font.render("Game over..", True, (255, 0, 0))
            screen.blit(lost_text, (text_x, text_y))
            show_frame()
            pygame.time.wait(1000)

            if created_display:
                pygame.quit()

            return won

        show_frame()
        clock.tick(60)

    if created_display:
        pygame.quit()

    return won


if __name__ == "__main__":
    raise SystemExit(main())
